image: tianon/latex
before_script:
- wget https://www.stackage.org/stack/linux-x86_64 -O /bin/stack
- stack install
build_paper:
    script: stack exec -- bt
    artifacts:
        paths:
        - thesis.pdf
