image: tianon/latex
before_script:
- for i in 1 2 3; do apt-get update -qq && apt-get install -y -qq wget && break || sleep 5; done
- wget https://www.stackage.org/stack/linux-x86_64 -O /bin/stack
- chmod u+x /bin/stack
- ls -l /bin | grep stack
- stack install
build_paper:
    script: stack exec -- bt
    artifacts:
        paths:
        - thesis.pdf
